# An example GitHub Actions YAML
name: Push to ECR
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Push to ECR
      run: |
        $(aws ecr get-login --no-include-email --region us-west-2)
        docker build -t my-sagemaker-container .
        docker tag my-sagemaker-container:latest $ECR_REPOSITORY:latest
        docker push $ECR_REPOSITORY:latest
